---
services:
  << service_name >>:
    image: docker.io/dgtlmoon/changedetection.io:0.55.8
    restart: << restart_policy >>
    env_file:
      - .env
    environment:
      - TZ=<< container_timezone >>
      - BASE_URL=<< base_url >>
      - HIDE_REFERER=<< hide_referer | lower >>
      - FETCH_WORKERS=<< fetch_workers >>
      - MINIMUM_SECONDS_RECHECK_TIME=<< minimum_seconds_recheck_time >>
      <%- if use_x_settings %>
      - USE_X_SETTINGS=1
      <%- endif %>
      <%- if browser_mode == 'sidecar' %>
      - PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000
      <%- elif browser_mode == 'external' %>
      - PLAYWRIGHT_DRIVER_URL=<< playwright_driver_url >>
      <%- endif %>
    volumes:
      <%- if volume_mode == 'mount' %>
      - << volume_mount_path >>/datastore:/datastore
      <%- else %>
      - << service_name >>_data:/datastore
      <%- endif %>
    <%- if npm_proxy_enabled %>
    networks:
      default:
      npm-proxy:
        aliases:
          - changedetection-web
    <%- endif %>
    <%- if not npm_proxy_enabled %>
    ports:
      - "<< ports_http >>:5000"
    <%- endif %>

  <%- if browser_mode == 'sidecar' %>
  browser-sockpuppet-chrome:
    image: docker.io/dgtlmoon/sockpuppetbrowser:latest
    restart: << restart_policy >>
    environment:
      - SCREEN_WIDTH=<< browser_screen_width >>
      - SCREEN_HEIGHT=<< browser_screen_height >>
      - SCREEN_DEPTH=<< browser_screen_depth >>
      - MAX_CONCURRENT_CHROME_PROCESSES=<< browser_max_concurrency >>
  <%- endif %>

<%- if volume_mode == 'local' %>
volumes:
  << service_name >>_data:
    driver: local
<%- elif volume_mode == 'nfs' %>
volumes:
  << service_name >>_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<< volume_nfs_server >>,nfsvers=4,<< volume_nfs_options >>
      device: ":<< volume_nfs_path >>/datastore"
<%- endif %>

<%- if npm_proxy_enabled %>
networks:
  default:
  npm-proxy:
    name: << npm_proxy_network >>
    external: true
<%- endif %>
