---
services:
  << service_name >>:
    image: ghcr.io/donkie/spoolman:0.24.0
    restart: << restart_policy >>
    environment:
      - TZ=<< container_timezone >>
      - PUID=<< puid >>
      - PGID=<< pgid >>
      - SPOOLMAN_HOST=0.0.0.0
      - SPOOLMAN_PORT=8000
      - SPOOLMAN_DB_TYPE=<< database_type >>
      - SPOOLMAN_LOGGING_LEVEL=<< logging_level >>
      - SPOOLMAN_AUTOMATIC_BACKUP=<< automatic_backup | upper >>
      - SPOOLMAN_METRICS_ENABLED=<< metrics_enabled | upper >>
      - EXTERNAL_DB_URL=<< external_db_url >>
      - EXTERNAL_DB_NAME=<< external_db_name >>
      - EXTERNAL_DB_SYNC_INTERVAL=<< external_db_sync_interval >>
      <%- if base_path %>
      - SPOOLMAN_BASE_PATH=<< base_path >>
      <%- endif %>
      <%- if cors_origin %>
      - SPOOLMAN_CORS_ORIGIN=<< cors_origin >>
      <%- endif %>
      <%- if allowed_hosts %>
      - SPOOLMAN_ALLOWED_HOSTS=<< allowed_hosts >>
      <%- endif %>
      <%- if database_type != 'sqlite' %>
      - SPOOLMAN_DB_HOST=<< database_host >>
      - SPOOLMAN_DB_PORT=<< database_port >>
      - SPOOLMAN_DB_NAME=<< database_name >>
      - SPOOLMAN_DB_USERNAME=<< database_username >>
      - SPOOLMAN_DB_PASSWORD=${SPOOLMAN_DB_PASSWORD}
      <%- if database_query %>
      - SPOOLMAN_DB_QUERY=<< database_query >>
      <%- endif %>
      <%- endif %>
    volumes:
      <%- if volume_mode == 'mount' %>
      - << volume_mount_path >>/data:/home/app/.local/share/spoolman
      <%- else %>
      - << service_name >>_data:/home/app/.local/share/spoolman
      <%- endif %>
    <%- if npm_proxy_enabled %>
    networks:
      default:
      npm-proxy:
        aliases:
          - spoolman-web
    <%- endif %>
    <%- if not npm_proxy_enabled %>
    ports:
      - "<< ports_http >>:8000"
    <%- endif %>

<%- if volume_mode == 'local' %>
volumes:
  << service_name >>_data:
    driver: local
<%- elif volume_mode == 'nfs' %>
volumes:
  << service_name >>_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<< volume_nfs_server >>,nfsvers=4,<< volume_nfs_options >>
      device: ":<< volume_nfs_path >>/data"
<%- endif %>

<%- if npm_proxy_enabled %>
networks:
  default:
  npm-proxy:
    name: << npm_proxy_network >>
    external: true
<%- endif %>
