---
services:
  << service_name >>:
    image: ghcr.io/tinyauthapp/tinyauth:v5.1.2
    restart: << restart_policy >>
    env_file:
      - .env
    environment:
      - TINYAUTH_DATABASE_PATH=/data/tinyauth.db
    volumes:
      <%- if volume_mode == 'mount' %>
      - << volume_mount_path >>:/data
      <%- else %>
      - << service_name >>_data:/data
      <%- endif %>
    <%- if npm_proxy_enabled %>
    networks:
      default:
      npm-proxy:
        aliases:
          - tinyauth-web
    <%- endif %>
    <%- if not npm_proxy_enabled %>
    ports:
      - "<< ports_http >>:3000"
    <%- endif %>

<%- if volume_mode == 'local' %>
volumes:
  << service_name >>_data:
    driver: local
<%- elif volume_mode == 'nfs' %>
volumes:
  << service_name >>_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<< volume_nfs_server >>,nfsvers=4,<< volume_nfs_options >>
      device: ":<< volume_nfs_path >>"
<%- endif %>

<%- if npm_proxy_enabled %>
networks:
  default:
  npm-proxy:
    name: << npm_proxy_network >>
    external: true
<%- endif %>
