---
services:
  << service_name >>:
    image: ghcr.io/karakeep-app/karakeep:0.32.0
    restart: << restart_policy >>
    env_file:
      - .env
    environment:
      - DATA_DIR=/data
      - MEILI_ADDR=http://<< service_name >>_meilisearch:7700
      - BROWSER_WEB_URL=http://<< service_name >>_chrome:9222
    volumes:
      <%- if volume_mode == 'mount' %>
      - << volume_mount_path >>/data:/data
      <%- else %>
      - << service_name >>_data:/data
      <%- endif %>
    networks:
      << service_name >>_backend:
      <%- if npm_proxy_enabled %>
      npm-proxy:
        aliases:
          - karakeep-web
      <%- endif %>
    <%- if not npm_proxy_enabled %>
    ports:
      - "<< ports_http >>:3000"
    <%- endif %>

  << service_name >>_chrome:
    image: ghcr.io/karakeep-app/karakeep-chrome:release
    restart: << restart_policy >>
    command:
      - --disable-gpu
      - --disable-dev-shm-usage
      - --hide-scrollbars
      - --disable-blink-features=AutomationControlled
      - --window-size=1440,900
    networks:
      - << service_name >>_backend

  << service_name >>_meilisearch:
    image: getmeili/meilisearch:v1.41.0
    restart: << restart_policy >>
    env_file:
      - .env
    environment:
      - MEILI_NO_ANALYTICS=true
    volumes:
      <%- if volume_mode == 'mount' %>
      - << volume_mount_path >>/meilisearch:/meili_data
      <%- else %>
      - << service_name >>_meilisearch:/meili_data
      <%- endif %>
    networks:
      - << service_name >>_backend

networks:
  << service_name >>_backend:
    driver: bridge
  <%- if npm_proxy_enabled %>
  npm-proxy:
    name: << npm_proxy_network >>
    external: true
  <%- endif %>

<%- if volume_mode == 'local' %>
volumes:
  << service_name >>_data:
    driver: local
  << service_name >>_meilisearch:
    driver: local
<%- elif volume_mode == 'nfs' %>
volumes:
  << service_name >>_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<< volume_nfs_server >>,nfsvers=4,<< volume_nfs_options >>
      device: ":<< volume_nfs_path >>/data"
  << service_name >>_meilisearch:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<< volume_nfs_server >>,nfsvers=4,<< volume_nfs_options >>
      device: ":<< volume_nfs_path >>/meilisearch"
<%- endif %>
